name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d ~/auto-deployment-demo ]; then
              git clone https://github.com/jianwei0510/auto-deployment-demo.git ~/auto-deployment-demo
            fi
            cd ~/auto-deployment-demo
            git pull origin main
            npm install --omit=dev
            mkdir -p data
            pm2 restart auto-deployment-demo || pm2 start app.js --name auto-deployment-demo
            pm2 save
